### PR TITLE
fix(pgsql): select from support view name

### PR DESCRIPTION
**Pull request by Cythia828**
https://github.com/DTStack/dt-sql-parser/issues/255

- select from 语句中在文档详细说明里体现了table_name包含了table_name和view_name，补全支持view_name

文档链接：https://www.postgresql.org/docs/current/sql-select.html
文档截图：

image
image

### CODE REVIEW

**Comment by Cythia828** [comment]
@HaydenOrz @liuxy0551 @mumiao

**Comment by HaydenOrz** [comment]
#254

**Comment by HaydenOrz** [comment]
贴一下文档链接吧

**Comment by HaydenOrz** [comment]
+1

**Comment by mumiao** [comment]
+1

**Pull request merged**
